### ISSUE TITLE
Do not mix up props before and after spread operator

### ISSUE THREAD

**Issue by pahan35** [leo-buneev/eslint-plugin-sort-keys-fix#15]
Relates to #3

## Versions
eslint-plugin-sort-keys-fix: 1.1.0
Node.js: 13.7.0 

### Dependencies
`npm i -D babel-eslint eslint eslint-plugin-sort-keys-fix`

.eslintrc
```
{
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 8,
    "sourceType": "module",
  },
  "plugins": [
    "sort-keys-fix"
  ],
  "env": {
      "browser": true,
      "es6": true,
    },
  "rules": {
    "sort-keys-fix/sort-keys-fix": "error"
  }
}
```

### Code to reproduce
```
var z = {}
var obj = {b:1, ...z, a:1}
```

### Expected

No violations

### Actual

> ESLint: Expected object keys to be in ascending order. 'a' should be before 'b'.(sort-keys-fix/sort-keys-fix)

![image](https://user-images.githubusercontent.com/13823215/79641308-63a8a000-819f-11ea-9581-046a042c1dbb.png)

### Motivation

It's problematic in cases where we want to allow overriding some in the target object
```
function foo(overridings) {
  const target = {b: 7, ...overridings, a: 5}
}
```
Also, current behavior causes bugs like described in https://github.com/leo-buneev/eslint-plugin-sort-keys-fix/issues/2#issuecomment-615877695

**Comment by leo-buneev** [comment]
Thx @pahan35 . Released in 1.1.1.
